services:
  - type: web
    name: clonebot
    runtime: docker
    plan: starter
    envVars:
      - key: PORT
        value: "1000"
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: HOME_GUILD_ID
        sync: false
      - key: DB_PATH
        value: /data/clonebot.db
    disk:
      name: clonebot-data
      mountPath: /data
      sizeGB: 1
