services:
  - type: web
    name: clonebot
    runtime: docker
    plan: free
    envVars:
      - key: PORT
        value: "1000"
      - key: TOKEN
        sync: false
      - key: OWNER_ID
        sync: false
      - key: HOME_GUILD_ID
        sync: false
      - key: TURSO_DATABASE_URL
        sync: false
      - key: TURSO_AUTH_TOKEN
        sync: false
